spring.application.name=gateway-service
server.port=8080

management.endpoints.web.exposure.include=health,info

# Route everything under /api/auth/** and /api/users/** to auth-service
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**
# Route everything under /api/projects/** to project-service
spring.cloud.gateway.server.webmvc.routes[1].id=project-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${PROJECT_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/projects/**